---
format:   
    pdf:    
      include-before-body:       
        - title.tex.txt     
      include-in-header:        
       text: |        
        \usepackage{graphicx}        
        \usepackage{fancyhdr}         
        \usepackage{sectsty}        
        \usepackage{titlesec}        
        \usepackage{tocloft}        
        \usepackage{setspace}         
        \usepackage[style=apa]{biblatex}         
        \addbibresource{references.bib}
        \pagestyle{fancy}         
        \fancyhf{}          
        \addtokomafont{disposition}{\rmfamily}
      keep-tex: true     
      toc: true 
      toc-title: "Innhold"    
      toc-depth: 3     
      number-sections: true   
      number-depth: 3     
      geometry: "left=2.5cm,right=2.5cm,top=2.5cm,bottom=2.5cm"     
      fontsize: 12pt     
      colorlinks: true    
      bibliography: Referanser.bib     
      bibliographystyle: apa.cls
---

## Sammendrag

Her kommer tekst

## Innledning

Her kommer tekst

```{r echo=FALSE, warning=FALSE, message=FALSE, error=FALSE, include=FALSE}
#tømmer enviroment
rm(list = ls())
#Alle mulig nødvendige pakker.

library(tidyverse)
library(car)


#setter inn for at en kan bruke norske bokstaver(særslikt maskinen denne filen er laget på)
Sys.setlocale("LC_ALL", "en_US.UTF-8")

```

```{r echo=FALSE, warning=FALSE, message=FALSE, error=FALSE}
#leser inn fila
NSD3127 <- read_csv("Norsk medborgerpanel runde 26, 2023/NSD3127.csv")
#ser på fila
#View(NSD3127)
```

```{r echo=FALSE, warning=FALSE}
#Lager datasett med de variablene vi skal bruke og kaller denne for runde_26

runde_26 <- NSD3127 %>% select(r26_bgciv,
                                    r26k2_bgurb, 
                                    r26k2_bgchi,
                                    r26P1,
                                    r26P2, 
                                    r26P3,
                                    #r26P5_1,
                               r26P5_2, 
                                    r26P4_1,#r26P4_2,
                                    #r26k2_cemes_a,r26k2_cemes_b,r26k2_cemes_c,r26k2_cemes_d,r26k2_cemes_e, r26k2_cemes_f,r26k2_cemes_g,r26k2_cemes_h,r26k2_cemes_i,
                               r26k2_cemes_j,#r26_pccos,r26_pccop,r26_pccoo,
                               r26k2_pcpar,r26k2_bginc,r26k2_pcwcc)

#endrer videre navnene på variablene

runde_26 <- runde_26 %>% rename(sivilstatus = r26_bgciv, 
         geo_omr = r26k2_bgurb, 
         barn = r26k2_bgchi,
         kjønn =r26P1,
         landsdel =r26P2, 
         fylke =r26P3,
         #fødselsår_1 =r26P5_1,
         fødselsår_2 = r26P5_2, 
         h_utd_1 = r26P4_1, 
         #h_utd_2 = r26P4_2,
         #tiltak_kostnadseff = r26k2_cemes_a,
         #tiltak_støtte = r26k2_cemes_b,
         #tiltak_ikke_skade_okonomi = r26k2_cemes_c,
         #tiltak_arbeidspl = r26k2_cemes_d,
         #tiltak_utslippskutt = r26k2_cemes_e, 
         #tiltak_globalt_ansvar = r26k2_cemes_f,
         #tiltak_teknologi_kutt = r26k2_cemes_g,
         #tiltaket_ekspert = r26k2_cemes_h,
         #tiltak_forskjeller = r26k2_cemes_i,
         tiltak_norsk_natur = r26k2_cemes_j,
         #tillit_storting = r26_pccos,
         #tillit_politikere = r26_pccop,
         #tillit_andre = r26_pccoo,
         st_valg_parti = r26k2_pcpar,
         inntekt = r26k2_bginc,
         klimaendringer = r26k2_pcwcc)

#view(runde_26)
```

```{r echo=FALSE, warning=FALSE}
# Endrer alle verdier med 97 og 98 til NA for at ikke alle radene skal bli borte.

spesifikke_verdier <- c(97, 98)

# Loop gjennom kolonnene og erstatt de spesifikke verdiene med NA
for (col in colnames(runde_26)) {
  runde_26[[col]][runde_26[[col]] %in% spesifikke_verdier] <- NA
}
```

```{r echo=FALSE, warning=FALSE}
# endre dataene til gift samboer som 1 og resten som 0 i ny kolonne
runde_26 <- runde_26 %>%
  mutate(gift_samboer = case_when(
    sivilstatus %in% c(1, 2, 5, 6, 7) ~ 0,
    TRUE ~ 1
  ))
```

```{r echo=FALSE, warning=FALSE}
# endre dataene til har barn og har ikke barn i ny kolonne, 0 for ikke barn og 1 for barn
runde_26 <- runde_26 %>%
  mutate(har_barn_hjemme = case_when(
    barn %in% c(0) ~ 0,
    TRUE ~ 1
  ))

```

```{r echo=FALSE, fig.width=6, fig.height=4}
#lage introfiguren med hvor bekymret er du for klimaendringer hvor
#man teller opp hvor mange man har av hvert svar

# først fjerner NA-verdier fra kolonnen så de ikke kommer med i tellingen
runde_26_clean <- runde_26 %>% filter(!is.na(klimaendringer))

# Telling så uten NA-verdier
count <- count(runde_26_clean, klimaendringer)

# Lager derretter et stolpediagram med forklaring på hva verdiene betyr
ggplot(count, aes(x = klimaendringer, y = n)) +
  geom_bar(stat = "identity", fill = "aquamarine2") +
  labs(title = "Hvor bekymret er du for 'klimaendringer'?",
       subtitle = "Antall forkomster med svar fra medborgerpanelet runde 26",
       x = "Bekymringsnivå",
       y = "Antall",
       caption = "Bekymringsnivå: 1 = Ikke bekymret, 5 = Veldig bekymret") +
  theme_minimal() +  # Minimalt tema
  theme(plot.title = element_text(size = 16, hjust = 0.5, face = "bold"),  # Justering av tittelstørrelse og plassering
        axis.title = element_text(size = 14),  # Justering av akseetikettstørrelse
        plot.subtitle = element_text(size = 14, hjust = 0.5),  # Justering av undertittelstørrelse og plassering
        axis.text = element_text(size = 12),   # Justering av aksetekststørrelse
        plot.caption = element_text(size = 10, hjust = 0))  # Justering av bildetekststørrelse og plassering

```

```{r}

#nå skal vi lage alle faktorene man eventuelt blir å trenge

data1 <- runde_26 %>%
  mutate(født = case_when(
    fødselsår_2 == 1 ~ '1959_og_før',
    fødselsår_2 == 2 ~ '1960_1989',
    TRUE ~ '1990_og_etter'
  )) %>%
  mutate(født = factor(født, levels = c('1959_og_før', '1960_1989', '1990_og_etter'))) %>%
  mutate(gift_samboer = case_when(
    sivilstatus %in% c(1, 2, 5, 6, 7) ~ 0,
    TRUE ~ 1
  )) %>%
   mutate(utdanning = factor(h_utd_1, 
                            levels = c(1, 2, 3),
                            labels = c("grunnskole", "videregående", "høyere"))) %>%
  mutate(utdanning = fct_relevel(utdanning, "høyere")) %>%
  mutate(inntekter = factor(inntekt, 
                            levels = c(1, 2, 3, 4 ,5 ,6 ,7 ,8),
                            labels = c("Mindre enn 150 000",
                                       "150 001 - 300 000",
                                       "300 001 - 400 000",
                                       "400 001 - 500 000",
                                       "500 001 - 600 000",
                                       "600 001 - 700 000",
                                       "700 001 - 1 000 000",
                                       "Mer enn 1 000 000"))) %>%
  mutate(inntekter = fct_relevel(inntekter, "Mindre enn 150 000"))
```

## Teori

## Metode og datagrunnlag

## Deskriptiv statistikk

## Episriske resultater

## Resultat

## Grafisk analyse

## Diskusjon

## Begrensninger ved analysen

## Referanser
